version: "3.5"

services:
  guessthesongmarusia:
    container_name: guessthesongmarusia
    build: 
      context: .
    restart: unless-stopped
    command: "./marusia"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    env_file:
      - .env
    volumes:
      - postgresdatamarusia:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports: 
      - "10001:80"
    env_file:
      - .env
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  postgresdatamarusia:
  pgadmindata: